### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by seygodin** [jaehyun513/STUNT#1]
I'm very interested in your research. Would you explain the rules for building a customed DATASET?

**Comment by jaehyun513** [comment]
Thank you for your interest in our work! Here's a concise explanation of building a custom dataset:

1. Ensure your unlabeled data is in a 1-dimensional tabular format. Your dataset should be in the form of N x d, where N represents the number of unlabeled data points and d corresponds to the number of column features.
2. Divide the unlabeled data into a training sample and a validation sample for pseudo-validation.
3. Generate pseudo-labels for the pseudo-validation set.
4. Execute the main code.
5. Adapt the model with your labeled samples.

Keep in mind that tabular data can be preprocessed in various ways. In our study, we utilized one-hot encoding for categorical data and min-max scaling for numerical values. However, our method can be applied to any preprocessing approach. We recommend discovering the most effective preprocessing technique for your specific data.

Thank you once again for your interest, and please don't hesitate to reach out via email or any other means if you have further questions!
