### ISSUE TITLE
Regarding the number of few-shot.

### ISSUE THREAD

**Issue by EeyoreLee** [jaehyun513/STUNT#3]
hi, jaehyun. If there are around 600 labeled data, is this model suitable? And all the data labeled and unlabed are about 2000 ?

**Comment by jaehyun513** [comment]
Hi, it is possible to run STUNT with 600 labeled data.
However, STUNT is more suitable when the number of limited data is really small (e.g., 1-shot, 5-shot).
I recommend you to also try other algorithms like CatBoost, if you have enough labeled data.
Thanks!
